spring:
  application:
    name: cards
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cards
    driverClassName: org.h2.Driver
    username: admin
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

