spring:
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb?createDatabaseIfNotExist=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
    properties:
      hibernate:
        format_sql: true
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"