build:
  version: "2.0"

accounts:
  message: "Welcome to Banking Application accounts related Development APIs "
  contactDetails:
    name: "Mohamed Saber - Developer"
    email: "mohamed.saber.mohamed.dev@gmail.com"