build:
  version: "2.0"

cards:
  message: "Welcome to Banking Application Cards related Production APIs "
  contactDetails:
    name: "Mohamed Saber - Developer"
    email: "mohamed.saber.mohamed.dev@gmail.com"