build:
  version: "1.0"

cards:
  message: "Welcome to Banking Application cards related local APIs "
  contactDetails:
    name: "Mohamed Saber - Developer"
    email: "mohamed.saber.mohamed.dev@gmail.com"